### ISSUE TITLE
Перестал работать в новой версии Хабра

### ISSUE THREAD

**Issue by caxaline** [allati/habrtree#1]
Добрый день!
Пользуюсь много лет скриптом.
Видимо хабр поменял стили и он снова перестал работать. Вы не планируете исправить скрипт?
Сам я на это не способен, к сожалению, и буду очень признателен.

**Comment by allati** [comment]
Приветствую.

Обновил скрипт. Я уже не помню, как оно работало со старым дизайном, но вроде бы как-то похоже на то, как работает сейчас. Проверял на FF 57 с обновленным Greasemonkey.

В коде остались блоки, связанные со скрытием/отображением панели или ссылок для добавления комментариев, но без аккаунта на хабре я проверить корректность их работы не могу. Если в отношении этой панели что-то сломалось - переоткрывайте заявку.

**Comment by caxaline** [comment]
@allati Всё работает, спасибо!
